build: bind private decomment tool

diff --git a/src/kernel-7/conf/Makefile.template b/src/kernel-7/conf/Makefile.template
--- a/src/kernel-7/conf/Makefile.template
+++ b/src/kernel-7/conf/Makefile.template
@@ -142,7 +142,7 @@ INSTALL_FLAGS = -c -m 444
 # DRIVER_PRIVATE stuff
 #
 UNIFDEF   = /usr/bin/unifdef
-DECOMMENT = /usr/local/bin/decomment
+DECOMMENT ?= /usr/local/bin/decomment
 
 #
 # Header files that are unifdef'ed and installed in INCDIR
@@ -857,13 +857,11 @@ installhdrs: DSTROOT install_mi_hdrs install_md_hdrs
 install_mi_hdrs: DSTROOT install_mi_std_hdrs
 
 #
-# Note the outer for loop of this operation has to be tolerant of non-zero
-# returns because unifdef returns 1 if it makes a change. I don't think this
-# is a problem, but we might want to modify unifdef instead of having the
-# following "-for" expression...
+# unifdef returns 1 when it makes a change.  In that case decomment processes
+# the partial output; a failed fallback must stop header installation.
 #
 install_mi_std_hdrs: DSTROOT $(MIG_HFILES_EXP) $(MACH_DEBUG_HFILE)
-	@-for i in ${EXPORT}; 						\
+	@for i in ${EXPORT}; 						\
 	do								\
 	    EXPDIR=`pwd`/exports;					\
 	    [ -d $$EXPDIR ] || $(MKDIRS) $$EXPDIR;				\
@@ -879,9 +877,10 @@ install_mi_std_hdrs: DSTROOT $(MIG_HFILES_EXP) $(MACH_DEBUG_HFILE)
 			[ -d $$DSTDIR ] || $(MKDIRS) $$DSTDIR;		\
 			echo garbage > $$EXPDIR/$$j.strip;		\
 			$(UNIFDEF) -UKERNEL_PRIVATE -UDRIVER_PRIVATE	\
-				$$j > $$EXPDIR/$$j || 			\
+				$$j > $$EXPDIR/$$j || { 		\
 				$(DECOMMENT) $$EXPDIR/$$j  r > 		\
-				$$EXPDIR/$$j.strip; 			\
+				$$EXPDIR/$$j.strip || exit 1; 		\
+				}; 					\
 			if [ -s $$EXPDIR/$$j.strip ]; 			\
 			then (						\
 			    cd $$EXPDIR;				\
@@ -893,7 +892,7 @@ install_mi_std_hdrs: DSTROOT $(MIG_HFILES_EXP) $(MACH_DEBUG_HFILE)
 			rm -f $$EXPDIR/$$j.strip;			\
 		    done;						\
 		fi;							\
-	    );								\
+	    ) || exit 1;						\
 	done
 	for i in ${EXPORT_LIB};						\
 	do								\
@@ -959,7 +958,7 @@ install_md_hdrs: DSTROOT install_md_std_hdrs \
 	$(MACHINE_INSTALLHDRS)
 
 install_md_std_hdrs: DSTROOT
-	@-for i in `echo ${MACHINE_EXPORT}`; 				\
+	@for i in `echo ${MACHINE_EXPORT}`; 				\
 	do								\
 	    EXPDIR=`pwd`/exports;					\
 	    [ -d $$EXPDIR ] || $(MKDIRS) $$EXPDIR;				\
@@ -974,8 +973,9 @@ install_md_std_hdrs: DSTROOT
 			DSTDIR=$(DSTROOT)$(INCDIR)/$$i;			\
 			[ -d $$DSTDIR ] || $(MKDIRS) $$DSTDIR;		\
 			echo garbage > $$EXPDIR/$$j.strip;		\
-			$(UNIFDEF) -UKERNEL_PRIVATE -UDRIVER_PRIVATE $$j > $$EXPDIR/$$j || \
-			$(DECOMMENT) $$EXPDIR/$$j  r > $$EXPDIR/$$j.strip; \
+			$(UNIFDEF) -UKERNEL_PRIVATE -UDRIVER_PRIVATE $$j > $$EXPDIR/$$j || { \
+			$(DECOMMENT) $$EXPDIR/$$j  r > $$EXPDIR/$$j.strip || exit 1; \
+			}; \
 			if [ -s $$EXPDIR/$$j.strip ]; 			\
 			then (						\
 			    cd $$EXPDIR;				\
@@ -987,7 +987,7 @@ install_md_std_hdrs: DSTROOT
 			rm -f $$EXPDIR/$$j.strip;			\
 		    done;						\
 		fi;							\
-	    );								\
+	    ) || exit 1;						\
 	done
 	for i in ${MACHINE_MIGDIRS};					\
 	do 								\
